.\" Copyright holder 2001-2011 Vedder Bruno.
.\" Work continued by 2016-2018 Carlos Donizete Froes [a.k.a coringao]
.\"
.\" This file is part of Osmose, a Sega Master System/Game Gear software
.\" emulator.
.\"
.\" Osmose is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" any later version.
.\"
.\" Osmose is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Osmose.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Many thanks to Vedder Bruno, the original author of Osmose Emulator.
.\"
.TH osmose-emulator "6" "September 2018" "OSMOSE EMULATOR" "Sega Master System and Game Gear console emulator"
.SH NAME
osmose-emulator \- is for Master System and Game Gear consoles with excellent performance and compatibility in emulated games.
.br
.SH SYNOPSIS
.B osmose-emulator
.RI [ description ]
.RI [ command ]
.RI [ keyboard ]
.RI [ author ]
.br
.PP
.SH DESCRIPTION
.br
A multi-machine emulator for platforms of Sega consoles (Master System and Game Gear) and compatible for all games.
.PP
Simulates hardware extremely accurately which ensures that these classic games are represented exactly like they were on the real systems.
.PP
Osmose Emulator has a clean graphical user interface based on QT and a simplified setup process, and supports ROM archives in the SMS and GG formats.
.br
.PP
.SH COMMAND
.br
Basic emulator command.
.TP
.B
Ctrl+O
- Find the directory where is located the roms.
.TP
.B
Ctrl+R
- Reset the game.
.TP
.B
Ctrl+F
- Leaves the full screen mode and to return in window mode, press again.
.br
.SH KEYBOARD
Basic movement and action command. To enter configuration mode, button Ctrl + C.
.PP
.B Control P1: (Standard Mode)
.PP
.B	KEY					ACTION
.br
Pad1 UP				up arrow
.PP
Pad1 DOWN				down arrow
.PP
Pad1 LEFT				left arrow
.PP
Pad1 RIGHT			right arrow
.PP
Pad1 Button A			press letter Z
.PP
Pad1 Button B			press letter X
.PP
PAUSE/SELECT			press letter P
.PP
START (GameGear)		press letter S
.PP
.SH AUTHOR
Many thanks to Vedder Bruno, the original author of Osmose Emulator and continued by Carlos Donizete Froes [a.k.a coringao].
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao], for the Debian project (but may be used by others).
